using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;

public class Visualisers : MonoBehaviour
{
    public PlayerMovement playerMovement;
    public Timers timers;
    public GunManager gunManager;
    
    public TextMeshProUGUI Text1;
    public TextMeshProUGUI Text2;

    // Update is called once per frame
    void Update()
    {
        Text1.text  = "Multishot: "         + gunManager.Guns[gunManager.ActiveGun].GetComponent<Gun>().MultiShot;
        Text2.text  = "MultiShotInterval: " + gunManager.Guns[gunManager.ActiveGun].GetComponent<Gun>().MultiShotInterval;
    }
}
